

####################################
server:
  port: 9000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/joedayz/rsmortgage-config-repository
          searchPaths: rsmortgage-customer-service,rsmortgage-customer-account-service
          username: joedayz
          password: password123
